//
//  SanoParkTower.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class SanoParkTower: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _key: String?
    var _timestamp: String?
    var _value: String?
    
    class func dynamoDBTableName() -> String {

        return "seatproj-mobilehub-1468142045-Sano-Park-Tower"
    }
    
    class func hashKeyAttribute() -> String {

        return "_key"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_timestamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_key" : "key",
               "_timestamp" : "timestamp",
               "_value" : "value",
        ]
    }
}
